name: Publish docs-template website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  deploy:
    name: Publish main branch

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: caefleury.github.io/cis-ieee-unb/

    steps:
      - uses: actions/checkout@v4

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - name: install retypeapp with dotnet tool
        run: dotnet tool install retypeapp --global

      - name: build diretorias
        run: retype build ./diretorias/retype.yml --output ./public/diretorias

      - name: build recursos
        run: retype build ./recursos/retype.yml --output ./public/recursos

      - name: build projetos
        run: retype build ./projetos/retype.yml --output ./public/projetos

      - name: build operacoes
        run: retype build ./operacoes/retype.yml --output ./public/operacoes

      - name: build engenharia-de-dados
        run: retype build ./engenharia-de-dados/retype.yml --output ./public/engenharia-de-dados

      - name: build ia
        run: retype build ./ia/retype.yml --output ./public/ia

      - name: build machine-learning
        run: retype build ./machine-learning/retype.yml --output ./public/machine-learning

      - name: build analise-de-dados
        run: retype build ./analise-de-dados/retype.yml --output ./public/analise-de-dados

      - name: build data-engineering
        run: retype build ./data-engineering/retype.yml --output ./public/data-engineering

      - name: setup pages
        uses: actions/configure-pages@v4

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
